#!/bin/bash

# Cloudflare R2 Environment Variables Helper Script
# This script helps you understand what each variable should look like

echo "🚀 Cloudflare R2 Environment Variables Guide"
echo "============================================="
echo ""

echo "📝 Your .env file should contain:"
echo ""
echo "# These are the 5 variables you need:"
echo "S3_BUCKET_NAME=beats-surround-audio"
echo "S3_PUBLIC_URL=https://pub-XXXXXXXXX.r2.dev"
echo "S3_ENDPOINT=https://YOUR_ACCOUNT_ID.r2.cloudflarestorage.com" 
echo "S3_ACCESS_KEY_ID=your_access_key_here"
echo "S3_SECRET_ACCESS_KEY=your_secret_key_here"
echo ""

echo "🔍 Where to find each value:"
echo ""
echo "1️⃣  S3_BUCKET_NAME: 'beats-surround-audio' (you already created this)"
echo ""
echo "2️⃣  S3_PUBLIC_URL:"
echo "   • Go to Cloudflare Dashboard → R2 Object Storage"
echo "   • Click on your 'beats-surround-audio' bucket"
echo "   • Click 'Settings' tab"
echo "   • Click 'Allow Access' under 'Public access'"
echo "   • Copy the 'Public bucket URL' that appears"
echo "   • Should look like: https://pub-abc123def456.r2.dev"
echo ""
echo "3️⃣  S3_ENDPOINT:"
echo "   • Go to Cloudflare Dashboard (any page)"
echo "   • Look in the RIGHT SIDEBAR for 'Account ID'"
echo "   • Copy that Account ID"
echo "   • Format: https://YOUR_ACCOUNT_ID.r2.cloudflarestorage.com"
echo "   • Example: https://abc123def456789.r2.cloudflarestorage.com"
echo ""
echo "4️⃣ & 5️⃣  S3_ACCESS_KEY_ID and S3_SECRET_ACCESS_KEY:"
echo "   • Go to R2 Object Storage → 'Manage R2 API tokens'"
echo "   • Click 'Create API token'"
echo "   • Select 'R2 Token' template"
echo "   • Choose 'Object Read & Write' permissions"
echo "   • Include your account resources"
echo "   • Click 'Continue to summary' → 'Create Token'"
echo "   • ⚠️  COPY BOTH KEYS IMMEDIATELY - you won't see them again!"
echo ""

echo "✅ Test your configuration:"
echo "   • Save your .env file"
echo "   • Run: npm start"
echo "   • Look for 'R2 configuration' messages in the logs"
echo ""

echo "🆘 Need help? Check CLOUDFLARE_R2_SETUP.md for detailed instructions"
